import { CARD_SCRIPT } from './pluginUi.generated.js'
// Resource URIs are cache keys; v3 preserves intentional blank preview labels.
export const PLUGIN_UI_URI = 'ui://flowchart-ai/chart-card-v3.html'

export function pluginUiHtml(baseUrl: string): string {
  const origin = new URL(baseUrl).origin
  if (!/^https?:$/.test(new URL(origin).protocol)) throw new Error('Invalid public origin')
  const safeOrigin = origin.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;')
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>Flowchart AI</title>
<style>
:root{color-scheme:light dark;--bg:light-dark(#fcfcff,#171824);--ink:light-dark(#25243b,#eeedf8);--muted:light-dark(#6d6a81,#aaa6bf);--line:light-dark(#e4e0ed,#363348);--node:light-dark(#fff,#262336);--accent:light-dark(#7462c4,#b1a0f3)}
*{box-sizing:border-box}body{font:14px system-ui,sans-serif;margin:0;padding:18px;color:var(--ink);background:var(--bg)}
.card-heading{display:flex;align-items:center;gap:9px;margin-bottom:14px}.card-mark{color:var(--accent);font-size:23px}h2{font-size:18px;line-height:1.35;margin:0;overflow-wrap:anywhere}.eyebrow{margin:0 0 3px;color:var(--muted);font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.12em}
p{line-height:1.5}.preview{border:1px solid var(--line);border-radius:14px;overflow:hidden;background:var(--node)}.preview-toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px;border-bottom:1px solid var(--line);padding:9px 12px;color:var(--muted);font-size:11px}.preview-toolbar strong{font-weight:600}.zoom-tools{display:flex;gap:4px}.zoom-tools button{padding:4px 8px;margin:0;font-size:12px;border-color:var(--line);border-radius:6px}
.preview-frame{height:clamp(220px,55vw,340px);overflow:auto;background-image:radial-gradient(var(--line) .7px,transparent .7px);background-size:16px 16px}#diagram{display:block;width:100%;height:100%;min-width:100%;min-height:100%;padding:12px;overflow:visible}.preview-note{margin:0;padding:9px 12px;color:var(--muted);font-size:11px;border-top:1px solid var(--line)}
.preview-node>rect,.preview-node>polygon,.preview-node>path{fill:var(--node);stroke:var(--accent);stroke-width:1.8}.node-step>rect{fill:light-dark(#edf7f1,#203830);stroke:light-dark(#62a887,#75bfa0)}.node-decision>polygon{fill:light-dark(#fff3e5,#3c3027);stroke:light-dark(#d09a53,#deb075)}.node-note>rect{fill:light-dark(#fffbe2,#383527);stroke:light-dark(#c9bc65,#c5b86b)}.node-container>rect{fill:light-dark(#f5f3fb,#201e2d);fill-opacity:.62;stroke:var(--line);stroke-dasharray:7 5}.node-label{fill:var(--ink);font-size:12px;font-weight:550}.container-label{fill:var(--muted);font-size:12px;font-weight:650}.node-glyph{fill:var(--accent);font-size:20px}.preview-edge{fill:none;stroke:light-dark(#aaa1bf,#877e9e);stroke-width:1.7}.preview-edge.dashed{stroke-dasharray:6 4}.preview-arrow{fill:light-dark(#aaa1bf,#877e9e)}.edge-label{fill:var(--muted);font-size:10px;font-weight:550;paint-order:stroke;stroke:var(--node);stroke-width:4;stroke-linejoin:round}
#status{font-size:11px;color:var(--muted);margin:13px 0 10px}.actions{display:flex;gap:7px;flex-wrap:wrap}button{font:inherit;padding:9px 12px;border:1px solid var(--line);border-radius:9px;cursor:pointer;color:var(--ink);background:var(--node);transition:background .15s}button:hover{background:light-dark(#f1edf9,#302b43)}button:focus-visible{outline:2px solid var(--accent);outline-offset:3px}button:disabled{opacity:.45;cursor:default}#edit{background:var(--accent);color:light-dark(#fff,#211838);border-color:transparent;font-weight:600}#delete{color:light-dark(#a85466,#eba1b1)}#confirmation{margin-top:12px;border:1px solid light-dark(#d9a5ad,#815665);padding:12px;border-radius:10px}#confirmation p{font-size:12px;margin:0 0 10px}#confirm-delete{background:light-dark(#a85466,#cf7e91);color:#fff;border-color:transparent}
@media(max-width:360px){body{padding:12px}h2{font-size:16px}.actions button{flex:1}.preview-toolbar{padding:8px}.preview-frame{height:240px}}
@media(prefers-reduced-motion:reduce){button{transition:none}}
</style></head>
<body data-origin="${safeOrigin}"><header class="card-heading"><span class="card-mark" aria-hidden="true">✦</span><div><p class="eyebrow">Flowchart AI</p><h2 id="title">Flowchart</h2></div></header>
<section class="preview" aria-label="Diagram preview"><div class="preview-toolbar"><strong>Your diagram, at a glance</strong><div class="zoom-tools" role="group" aria-label="Preview zoom"><button id="zoom-out" disabled aria-label="Zoom out">−</button><button id="fit" disabled>Fit</button><button id="zoom-in" disabled aria-label="Zoom in">+</button></div></div><div class="preview-frame" tabindex="0" aria-label="Scrollable diagram preview"><svg id="diagram" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Diagram preview"></svg></div><p id="preview-note" class="preview-note">Waiting for diagram data…</p></section>
<p id="status" role="status">Waiting for private chart controls…</p><div class="actions"><button id="edit" disabled>Open browser editor</button><button id="delete" disabled>Delete chart…</button></div><div id="confirmation" hidden><p>Delete this chart permanently? All its view and edit links will stop working. Downloaded copies and chat content remain.</p><button id="confirm-delete">Delete permanently</button><button id="cancel-delete">Cancel</button></div>
<script>${CARD_SCRIPT.replace(/<\/script/gi, '<\\/script')}</script></body></html>`
}
