import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { act, fireEvent, render, screen, within } from '@testing-library/react'
import App from '../App'
import { LOCAL_DRAFT_KEY } from '../hooks/useLocalDraft'

const layout = vi.hoisted(() => ({ arrange: vi.fn() }))
vi.mock('../shared/layout', () => ({ arrangeChart: layout.arrange }))

vi.mock('reactflow', async (importOriginal) => {
  const original = await importOriginal<typeof import('reactflow')>()
  return { ...original, useReactFlow: () => ({ ...original.useReactFlow(), setCenter: () => Promise.resolve(true) }) }
})

const backup = { version: 1, savedAt: 1790917171000, diagramMode: 'architecture', flow: { nodes: [{ id: 'saved-api', type: 'service', label: 'Saved observatory API', position: { x: 120, y: 160 }, icon: 'icon-cloud' }], edges: [] } }
const advance = (ms = 500) => act(() => { vi.advanceTimersByTime(ms) })
function rename(label: string, next: string) {
  const text = screen.getByText(label)
  const node = text.closest('.react-flow__node') as HTMLElement
  fireEvent.doubleClick(text)
  // JSDOM does not measure React Flow nodes, so their wrappers remain hidden.
  const input = within(node).getByRole('textbox', { hidden: true })
  fireEvent.change(input, { target: { value: next } })
  fireEvent.keyDown(input, { key: 'Enter' })
}
beforeEach(() => { vi.useFakeTimers(); window.history.replaceState({}, '', '/'); localStorage.clear() })
afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); layout.arrange.mockReset(); localStorage.clear(); sessionStorage.clear() })

describe('Editor content history integration', () => {
  it('preserves an intervening manual edit when immediately undoing a deferred template insertion', async () => {
    let release!: (value: unknown) => void
    const pending = new Promise((resolve) => { release = resolve })
    layout.arrange.mockReturnValue(pending)
    render(<App />)
    fireEvent.click(screen.getByLabelText('Open template gallery'))
    await act(async () => { fireEvent.click(screen.getByRole('button', { name: 'Use The dream observatory template' })) })
    await vi.waitFor(() => expect(layout.arrange).toHaveBeenCalledOnce())
    fireEvent.click(screen.getByLabelText('Add Step Node'))
    await act(async () => {
      release({ nodes: [{ id: 'template-result', type: 'step', label: 'Template result', position: { x: 10, y: 20 } }], edges: [] })
      await pending
    })
    fireEvent.click(screen.getByRole('button', { name: 'Insert into Canvas' }))
    expect(document.querySelectorAll('.react-flow-wrapper .react-flow__node')).toHaveLength(2)
    fireEvent.click(screen.getByLabelText('Undo'))
    expect(screen.getByText('Step')).toBeInTheDocument()
    expect(screen.queryByText('Template result')).not.toBeInTheDocument()
    fireEvent.click(screen.getByLabelText('Redo'))
    expect(screen.getByText('Step')).toBeInTheDocument()
    expect(screen.getByText('Template result')).toBeInTheDocument()
  })

  it('ignores theme and node selection changes while preserving the redo branch', () => {
    render(<App />)
    fireEvent.click(screen.getByLabelText('Toggle Dark Mode'))
    advance()
    expect(screen.getByLabelText('Undo')).toBeDisabled()
    fireEvent.click(screen.getByLabelText('Add Step Node'))
    advance()
    fireEvent.click(screen.getByLabelText('Find nodes and actions'))
    fireEvent.change(screen.getByRole('combobox', { name: 'Find a node or action' }), { target: { value: 'Step' } })
    fireEvent.click(screen.getByRole('option', { name: /Step/ }))
    expect(document.querySelector('.react-flow__node.selected')).not.toBeNull()
    fireEvent.click(screen.getByLabelText('Toggle Dark Mode'))
    advance()
    fireEvent.click(screen.getByLabelText('Undo'))
    expect(screen.queryByText('Step')).not.toBeInTheDocument()
    expect(screen.getByLabelText('Undo')).toBeDisabled()
    expect(screen.getByLabelText('Redo')).not.toBeDisabled()
    fireEvent.click(screen.getByLabelText('Toggle Dark Mode'))
    advance()
    expect(screen.getByLabelText('Redo')).not.toBeDisabled()
    fireEvent.click(screen.getByLabelText('Redo'))
    rename('Step', 'Still editable after Redo')
    expect(screen.getByText('Still editable after Redo')).toBeInTheDocument()
  })

  it('restores the prior mode and live label callbacks when undoing a mode change', () => {
    render(<App />)
    fireEvent.click(screen.getByLabelText('Add Step Node'))
    advance()
    fireEvent.click(screen.getByLabelText('Architecture Mode'))
    fireEvent.click(screen.getByLabelText('Undo'))
    expect(screen.getByLabelText('Flowchart Mode')).toHaveAttribute('aria-pressed', 'true')
    rename('Step', 'Edited after mode Undo')
    expect(screen.getByText('Edited after mode Undo')).toBeInTheDocument()
    fireEvent.click(screen.getByLabelText('Undo'))
    expect(screen.getByText('Step')).toBeInTheDocument()
    fireEvent.click(screen.getByLabelText('Redo'))
    rename('Edited after mode Undo', 'Edited again after Redo')
    expect(screen.getByText('Edited again after Redo')).toBeInTheDocument()
  })

  it('recognizes uppercase Shift+Ctrl+Z for Redo after keyboard Undo', () => {
    render(<App />)
    fireEvent.click(screen.getByLabelText('Add Step Node'))
    fireEvent.keyDown(window, { key: 'z', ctrlKey: true })
    expect(screen.queryByText('Step')).not.toBeInTheDocument()
    fireEvent.keyDown(window, { key: 'Z', ctrlKey: true, shiftKey: true })
    expect(screen.getByText('Step')).toBeInTheDocument()
  })

  it('keeps the welcome prompt from stealing keyboard Redo after undoing the first manual node', () => {
    render(<App />)
    advance(60)
    expect(screen.getByPlaceholderText('An idea, a process, a world…')).toHaveFocus()
    fireEvent.click(screen.getByLabelText('Add Step Node'))
    fireEvent.keyDown(document.activeElement!, { key: 'z', ctrlKey: true })
    advance(60)
    expect(screen.queryByText('Step')).not.toBeInTheDocument()
    expect(screen.queryByPlaceholderText('An idea, a process, a world…')).not.toBeInTheDocument()
    expect(document.activeElement?.matches('input, textarea, [contenteditable="true"]')).toBe(false)
    fireEvent.keyDown(document.activeElement!, { key: 'Z', ctrlKey: true, shiftKey: true })
    expect(screen.getByText('Step')).toBeInTheDocument()
  })

  it('keeps the selected canvas intact when Delete is pressed on a proposal heading', async () => {
    localStorage.setItem(LOCAL_DRAFT_KEY, JSON.stringify(backup))
    render(<App />)
    fireEvent.click(screen.getByLabelText('Add Step Node'))
    fireEvent.click(screen.getByLabelText('Find nodes and actions'))
    fireEvent.change(screen.getByRole('combobox', { name: 'Find a node or action' }), { target: { value: 'Step' } })
    fireEvent.click(screen.getByRole('option', { name: /Step/ }))
    expect(document.querySelector('.react-flow-wrapper .react-flow__node.selected')).not.toBeNull()
    fireEvent.click(screen.getByRole('button', { name: 'Preview saved draft' }))
    const heading = screen.getByRole('heading', { name: 'Preview AI Proposal' })
    expect(heading).toHaveFocus()
    await act(async () => { fireEvent.keyDown(heading, { key: 'Delete', code: 'Delete' }) })
    expect(screen.getByText('Step')).toBeInTheDocument()
    expect(heading).toHaveFocus()
    expect(screen.getByRole('button', { name: 'Restore saved draft' })).toBeInTheDocument()
  })

  it('cuts a selected node with its incident connection and restores both with Undo', () => {
    const connected = { ...backup, diagramMode: 'flowchart', flow: {
      nodes: [{ id: 'source', type: 'step', label: 'Source step', position: { x: 0, y: 0 } }, { id: 'sink', type: 'step', label: 'Sink step', position: { x: 240, y: 0 } }],
      edges: [{ id: 'request', source: 'source', target: 'sink', label: 'Send request', protocol: 'HTTPS', commStyle: 'sync', style: 'default' }],
    } }
    localStorage.setItem(LOCAL_DRAFT_KEY, JSON.stringify(connected))
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Preview saved draft' }))
    fireEvent.click(screen.getByRole('button', { name: 'Restore saved draft' }))
    fireEvent.click(screen.getByLabelText('Find nodes and actions'))
    fireEvent.change(screen.getByRole('combobox', { name: 'Find a node or action' }), { target: { value: 'Source step' } })
    fireEvent.click(screen.getByRole('option', { name: /Source step/ }))
    fireEvent.keyDown(window, { key: 'x', ctrlKey: true })
    fireEvent.click(screen.getByLabelText('Toggle Explorer'))
    fireEvent.click(screen.getByRole('button', { name: 'JSON' }))
    const cut = JSON.parse((screen.getByRole('textbox', { name: 'Diagram JSON' }) as HTMLTextAreaElement).value)
    expect(cut.nodes.map((node: { id: string }) => node.id)).toEqual(['sink'])
    expect(cut.edges).toEqual([])
    fireEvent.click(screen.getByRole('button', { name: 'Close explorer' }))
    fireEvent.click(screen.getByLabelText('Undo'))
    fireEvent.click(screen.getByLabelText('Toggle Explorer'))
    fireEvent.click(screen.getByRole('button', { name: 'JSON' }))
    const restored = JSON.parse((screen.getByRole('textbox', { name: 'Diagram JSON' }) as HTMLTextAreaElement).value)
    expect(restored.nodes.map((node: { id: string }) => node.id)).toEqual(['source', 'sink'])
    expect(restored.edges).toEqual([expect.objectContaining({ id: 'request', source: 'source', target: 'sink', protocol: 'HTTPS', commStyle: 'sync' })])
  })

  it('moves container descendants with Cut so Paste does not duplicate the original child', () => {
    const nested = { ...backup, flow: { nodes: [
      { id: 'box', type: 'container', label: 'Cloud boundary', position: { x: 100, y: 100 }, width: 420, height: 300, containerKind: 'group' },
      { id: 'child', type: 'service', label: 'Unique child service', parentNode: 'box', position: { x: 40, y: 80 } },
      { id: 'outside', type: 'note', label: 'Outside note', position: { x: 620, y: 100 } },
    ], edges: [] } }
    localStorage.setItem(LOCAL_DRAFT_KEY, JSON.stringify(nested))
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Preview saved draft' }))
    fireEvent.click(screen.getByRole('button', { name: 'Restore saved draft' }))
    fireEvent.click(screen.getByLabelText('Find nodes and actions'))
    fireEvent.change(screen.getByRole('combobox', { name: 'Find a node or action' }), { target: { value: 'Cloud boundary' } })
    fireEvent.click(screen.getByRole('option', { name: /Cloud boundary/ }))
    fireEvent.keyDown(window, { key: 'x', ctrlKey: true })
    expect(document.querySelectorAll('.react-flow-wrapper .react-flow__node')).toHaveLength(1)
    expect(screen.getByText('Outside note')).toBeInTheDocument()
    expect(screen.queryByText('Unique child service')).not.toBeInTheDocument()
    fireEvent.keyDown(window, { key: 'v', ctrlKey: true })
    expect(document.querySelectorAll('.react-flow-wrapper .react-flow__node')).toHaveLength(3)
    expect(screen.getAllByText('Unique child service')).toHaveLength(1)
    fireEvent.click(screen.getByLabelText('Toggle Explorer'))
    fireEvent.click(screen.getByRole('button', { name: 'JSON' }))
    const pasted = JSON.parse((screen.getByRole('textbox', { name: 'Diagram JSON' }) as HTMLTextAreaElement).value)
    const parent = pasted.nodes.find((node: { type: string }) => node.type === 'container')
    const child = pasted.nodes.find((node: { label: string }) => node.label === 'Unique child service')
    expect(child.parentNode).toBe(parent.id)
    expect(child.position).toEqual({ x: 40, y: 80 })
    fireEvent.click(screen.getByRole('button', { name: 'Close explorer' }))
    fireEvent.click(screen.getByLabelText('Undo'))
    expect(document.querySelectorAll('.react-flow-wrapper .react-flow__node')).toHaveLength(1)
    fireEvent.click(screen.getByLabelText('Undo'))
    expect(document.querySelectorAll('.react-flow-wrapper .react-flow__node')).toHaveLength(3)
    expect(screen.getByText('Cloud boundary')).toBeInTheDocument()
    expect(screen.getByText('Unique child service')).toBeInTheDocument()
  })

  it('keeps Cancel out of history and makes draft restoration immediately undoable and redoable', () => {
    localStorage.setItem(LOCAL_DRAFT_KEY, JSON.stringify(backup))
    render(<App />)
    fireEvent.click(screen.getByLabelText('Add Step Node'))
    advance()
    fireEvent.click(screen.getByRole('button', { name: 'Preview saved draft' }))
    fireEvent.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(localStorage.getItem(LOCAL_DRAFT_KEY)).toBe(JSON.stringify(backup))
    fireEvent.click(screen.getByLabelText('Undo'))
    expect(screen.queryByText('Step')).not.toBeInTheDocument()
    fireEvent.click(screen.getByLabelText('Redo'))
    expect(screen.getByText('Step')).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: 'Preview saved draft' }))
    fireEvent.click(screen.getByRole('button', { name: 'Restore saved draft' }))
    expect(screen.getByLabelText('Architecture Mode')).toHaveAttribute('aria-pressed', 'true')
    expect(screen.queryByRole('button', { name: 'Preview saved draft' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByLabelText('Undo'))
    expect(screen.getByText('Step')).toBeInTheDocument()
    expect(screen.getByLabelText('Flowchart Mode')).toHaveAttribute('aria-pressed', 'true')
    fireEvent.click(screen.getByLabelText('Redo'))
    rename('Saved observatory API', 'Restored API remains editable')
    expect(screen.getByText('Restored API remains editable')).toBeInTheDocument()
    expect(screen.getByLabelText('Architecture Mode')).toHaveAttribute('aria-pressed', 'true')
  })

  it('cancels delayed history and draft writes when the restored board is cleared', () => {
    localStorage.setItem(LOCAL_DRAFT_KEY, JSON.stringify(backup))
    render(<App />)
    fireEvent.click(screen.getByRole('button', { name: 'Preview saved draft' }))
    fireEvent.click(screen.getByRole('button', { name: 'Restore saved draft' }))
    rename('Saved observatory API', 'A pending final edit')
    fireEvent.click(screen.getByLabelText('Clear All'))
    fireEvent.click(screen.getByRole('button', { name: 'Clear board' }))
    advance(2_000)
    expect(document.querySelector('.react-flow-wrapper .react-flow__node')).toBeNull()
    expect(localStorage.getItem(LOCAL_DRAFT_KEY)).toBeNull()
    expect(screen.getByLabelText('Undo')).toBeDisabled()
    expect(screen.getByLabelText('Redo')).toBeDisabled()
    fireEvent.click(screen.getByLabelText('Add Service Node'))
    fireEvent.click(screen.getByLabelText('Undo'))
    expect(screen.queryByText('Service')).not.toBeInTheDocument()
    expect(screen.queryByText('A pending final edit')).not.toBeInTheDocument()
  })

  it('restores mode and editable callbacks after undoing a locally mocked reviewed AI edit', async () => {
    const fetch = vi.fn().mockResolvedValue({ ok: true, json: async () => ({ message: JSON.stringify({ summary: 'Convert to an API', nodes: [{ id: '2', type: 'service', label: 'Reviewed API', position: { x: 10, y: 20 } }], edges: [] }), finishReason: 'stop' }) })
    vi.stubGlobal('fetch', fetch)
    render(<App />)
    fireEvent.click(screen.getByLabelText('Add Step Node'))
    fireEvent.click(screen.getByLabelText('Open diagram chat'))
    fireEvent.change(screen.getByLabelText('What would you like to change?'), { target: { value: 'Convert the step to an API' } })
    await act(async () => { fireEvent.click(screen.getByRole('button', { name: 'Preview changes' })) })
    fireEvent.click(screen.getByRole('button', { name: 'Apply changes' }))
    expect(screen.getByLabelText('Architecture Mode')).toHaveAttribute('aria-pressed', 'true')
    fireEvent.click(screen.getByLabelText('Undo'))
    expect(screen.getByLabelText('Flowchart Mode')).toHaveAttribute('aria-pressed', 'true')
    expect(screen.getByText('Step')).toBeInTheDocument()
    fireEvent.click(screen.getByLabelText('Redo'))
    rename('Reviewed API', 'Editable reviewed API')
    expect(screen.getByText('Editable reviewed API')).toBeInTheDocument()
    expect(fetch).toHaveBeenCalledOnce()
  })
})
