/**
 * Comprehensive Azure Icon Aliases Mapping
 * 
 * This file contains 500+ alias mappings for Azure service icons.
 * Each service has 2-5 common variations/aliases for flexible matching.
 * 
 * Usage: Import and merge with existing ALIASES in azureIconRegistry.ts
 */

export const AZURE_ICON_ALIASES: Record<string, string> = {
  // ============================================================================
  // COMPUTE
  // ============================================================================
  
  // Virtual Machines
  'vm': 'virtual-machine',
  'virtual machine': 'virtual-machine',
  'azure vm': 'virtual-machine',
  'azure virtual machine': 'virtual-machine',
  'vms': 'virtual-machine',
  'virtual machines': 'virtual-machines-(classic)',
  'classic vm': 'virtual-machines-(classic)',
  'classic virtual machine': 'virtual-machines-(classic)',
  
  // VM Scale Sets
  'vm scale set': 'vm-scale-sets',
  'vmss': 'vm-scale-sets',
  'virtual machine scale set': 'vm-scale-sets',
  'scale set': 'vm-scale-sets',
  'scale sets': 'vm-scale-sets',
  'azure vm scale set': 'vm-scale-sets',
  
  // Availability Sets
  'availability set': 'availability-sets',
  'av set': 'availability-sets',
  'azure availability set': 'availability-sets',
  
  // Disks
  'disk': 'disks',
  'managed disk': 'disks',
  'azure disk': 'disks',
  'data disk': 'disks',
  'os disk': 'disks',
  'disks': 'disks',
  'classic disk': 'disks-(classic)',
  'classic disks': 'disks-(classic)',
  'disk snapshot': 'disks-snapshots',
  'snapshot': 'disks-snapshots',
  'azure snapshot': 'disks-snapshots',
  'disk backup': 'disks-snapshots',
  
  // Images
  'image': 'images',
  'vm image': 'images',
  'virtual machine image': 'images',
  'classic image': 'vm-images-(classic)',
  'vm image classic': 'vm-images-(classic)',
  'classic vm image': 'vm-images-(classic)',
  'os image classic': 'os-images-(classic)',
  'classic os image': 'os-images-(classic)',
  'image definition': 'image-definitions',
  'shared image definition': 'image-definitions',
  'gallery image definition': 'image-definitions',
  'image version': 'image-versions',
  'gallery image version': 'image-versions',
  'shared image version': 'image-versions',
  'shared image gallery': 'shared-image-galleries',
  'sig': 'shared-image-galleries',
  'image gallery': 'shared-image-galleries',
  'compute gallery': 'azure-compute-galleries',
  'acg': 'azure-compute-galleries',
  'azure shared image gallery': 'azure-compute-galleries',
  'image template': 'image-templates',
  'azure image builder': 'image-templates',
  'aib': 'image-templates',
  'restore point': 'restore-points',
  'vm restore point': 'restore-points',
  'recovery point': 'restore-points',
  'restore point collection': 'restore-points-collections',
  'restore points collection': 'restore-points-collections',
  
  // App Services
  'app service': 'app-services',
  'web app': 'app-services',
  'azure web app': 'app-services',
  'azure app service': 'app-services',
  'web apps': 'app-services',
  'app services': 'app-services',
  'app service plan': 'app-service-plans',
  'asp': 'app-service-plans',
  'hosting plan': 'app-service-plans',
  'azure app service plan': 'app-service-plans',
  'app service environment': 'app-service-environments',
  'ase': 'app-service-environments',
  'azure app service environment': 'app-service-environments',
  'app service domain': 'app-service-domains',
  'custom domain': 'app-service-domains',
  'azure domain': 'app-service-domains',
  'app service certificate': 'app-service-certificates',
  'ssl certificate': 'app-service-certificates',
  'tls certificate': 'app-service-certificates',
  'static web app': 'static-apps',
  'swa': 'static-apps',
  'azure static web apps': 'static-apps',
  'static site': 'static-apps',
  
  // Function Apps
  'functions': 'function-apps',
  'azure functions': 'function-apps',
  'function app': 'function-apps',
  'serverless function': 'function-apps',
  'serverless functions': 'function-apps',
  'azure function apps': 'function-apps',
  
  // Kubernetes
  'kubernetes': 'kubernetes-services',
  'aks': 'kubernetes-services',
  'azure kubernetes': 'kubernetes-services',
  'azure kubernetes service': 'kubernetes-services',
  'k8s': 'kubernetes-services',
  'azure k8s': 'kubernetes-services',
  'aks automatic': 'aks-automatic',
  'automatic kubernetes': 'aks-automatic',
  'aks auto': 'aks-automatic',
  'aks istio': 'aks-istio',
  'istio service mesh': 'aks-istio',
  'aks network policy': 'aks-network-policy',
  'network policy': 'aks-network-policy',
  'fleet manager': 'kubernetes-fleet-manager',
  'kubernetes fleet': 'kubernetes-fleet-manager',
  'aks fleet': 'kubernetes-fleet-manager',
  'kubernetes hub': 'kubernetes-hub',
  'openshift': 'azure-red-hat-openshift',
  'red hat openshift': 'azure-red-hat-openshift',
  'azure openshift': 'azure-red-hat-openshift',
  'aro': 'azure-red-hat-openshift',
  
  // Containers
  'container instance': 'container-instances',
  'container instances': 'container-instances',
  'aci': 'container-instances',
  'azure container instances': 'container-instances',
  'azure container instance': 'container-instances',
  'container registry': 'container-registries',
  'acr': 'container-registries',
  'azure container registry': 'container-registries',
  'container apps': 'container-apps-environments',
  'azure container apps': 'container-apps-environments',
  'aca': 'container-apps-environments',
  'container service': 'container-services-(deprecated)',
  'acs': 'container-services-(deprecated)',
  'deprecated container service': 'container-services-(deprecated)',
  
  // Batch & Service Fabric
  'batch': 'batch-accounts',
  'azure batch': 'batch-accounts',
  'batch account': 'batch-accounts',
  'batch service': 'batch-accounts',
  'service fabric': 'service-fabric-clusters',
  'azure service fabric': 'service-fabric-clusters',
  'service fabric cluster': 'service-fabric-clusters',
  'sf': 'service-fabric-clusters',
  'managed service fabric': 'managed-service-fabric',
  'service fabric managed cluster': 'managed-service-fabric',
  'mesh application': 'mesh-applications',
  'service fabric mesh': 'mesh-applications',
  'azure mesh': 'mesh-applications',
  
  // Cloud Services
  'cloud service': 'cloud-services-(classic)',
  'cloud services': 'cloud-services-(classic)',
  'classic cloud service': 'cloud-services-(classic)',
  'azure cloud services': 'cloud-services-(classic)',
  
  // Spring Apps
  'spring apps': 'azure-spring-apps',
  'spring cloud': 'azure-spring-apps',
  'azure spring': 'azure-spring-apps',
  'azure spring apps': 'azure-spring-apps',
  
  // Virtual Desktop
  'host pool': 'host-pools',
  'wvd host pool': 'host-pools',
  'virtual desktop host pool': 'host-pools',
  'application group': 'application-group',
  'wvd application group': 'application-group',
  'desktop application group': 'application-group',
  'workspace': 'workspaces',
  'wvd workspace': 'workspaces',
  'virtual desktop workspace': 'workspaces',
  
  // Dedicated Hosts
  'host group': 'host-groups',
  'dedicated host group': 'host-groups',
  'dedicated host': 'hosts',
  'azure dedicated host': 'hosts',
  'hosts': 'hosts',
  
  // Maintenance & Encryption
  'maintenance configuration': 'maintenance-configuration',
  'maintenance window': 'maintenance-configuration',
  'disk encryption set': 'disk-encryption-sets',
  'encryption set': 'disk-encryption-sets',
  
  // Other Compute
  'automanaged vm': 'automanaged-vm',
  'azure autmanage': 'automanaged-vm',
  'automanaged virtual machine': 'automanaged-vm',
  'compute fleet': 'compute-fleet',
  'azure compute fleet': 'compute-fleet',
  'spot fleet': 'compute-fleet',
  'vm app definition': 'vm-app-definitions',
  'vm app version': 'vm-app-versions',
  'community image': 'community-images',
  
  // ============================================================================
  // STORAGE
  // ============================================================================
  
  'storage': 'storage-accounts',
  'storage account': 'storage-accounts',
  'azure storage': 'storage-accounts',
  'blob storage': 'storage-accounts',
  'azure blob': 'storage-accounts',
  'classic storage': 'storage-accounts-(classic)',
  'classic storage account': 'storage-accounts-(classic)',
  'files': 'azure-files',
  'azure files': 'azure-files',
  'file storage': 'azure-files',
  'azure file share': 'azure-files',
  'storage container': 'storage-container',
  'blob container': 'storage-container',
  'container': 'storage-container',
  'queue storage': 'storage-queue',
  'azure queue': 'storage-queue',
  'storage queue': 'storage-queue',
  'storage explorer': 'storage-explorer',
  'azure storage explorer': 'storage-explorer',
  'storage sync': 'storage-sync-services',
  'azure file sync': 'storage-sync-services',
  'storage sync service': 'storage-sync-services',
  'storage actions': 'storage-actions',
  'azure storage actions': 'storage-actions',
  'storage functions': 'storage-functions',
  'storage triggers': 'storage-functions',
  'storage hub': 'storage-hubs',
  'storage event hubs': 'storage-hubs',
  'storage mover': 'azure-storage-mover',
  'azure storage mover': 'azure-storage-mover',
  'data mover': 'azure-storage-mover',
  
  // Premium Storage
  'netapp': 'azure-netapp-files',
  'azure netapp': 'azure-netapp-files',
  'netapp files': 'azure-netapp-files',
  'anf': 'azure-netapp-files',
  'elastic san': 'elastic-san',
  'azure elastic san': 'elastic-san',
  'esan': 'elastic-san',
  'disk pool': 'disk-pool',
  'azure disk pool': 'disk-pool',
  'container storage': 'azure-container-storage',
  'azure container storage': 'azure-container-storage',
  'acs storage': 'azure-container-storage',
  
  // Data Transfer
  'data box': 'data-box',
  'databox': 'data-box',
  'azure databox': 'data-box',
  'physical data transfer': 'data-box',
  'data box gateway': 'azure-databox-gateway',
  'databox gateway': 'azure-databox-gateway',
  'db gateway': 'azure-databox-gateway',
  'stack edge': 'azure-stack-edge',
  'azure stack edge': 'azure-stack-edge',
  'data box edge': 'azure-stack-edge',
  'import export': 'import-export-jobs',
  'azure import export': 'import-export-jobs',
  'data import export': 'import-export-jobs',
  'storsimple': 'storsimple-device-managers',
  'azure storsimple': 'storsimple-device-managers',
  'storsimple manager': 'storsimple-device-managers',
  'storsimple data manager': 'storsimple-data-managers',
  'sdm': 'storsimple-data-managers',
  
  // ============================================================================
  // NETWORKING
  // ============================================================================
  
  'vnet': 'virtual-networks',
  'virtual network': 'virtual-networks',
  'azure vnet': 'virtual-networks',
  'azure virtual network': 'virtual-networks',
  'classic vnet': 'virtual-networks-(classic)',
  'classic virtual network': 'virtual-networks-(classic)',
  'vpn gateway': 'virtual-network-gateways',
  'virtual network gateway': 'virtual-network-gateways',
  'vnet gateway': 'virtual-network-gateways',
  'vpn': 'virtual-network-gateways',
  'azure vpn': 'virtual-network-gateways',
  'virtual private network': 'virtual-network-gateways',
  'site to site vpn': 'virtual-network-gateways',
  'vpn client': 'vpnclientwindows',
  'windows vpn client': 'vpnclientwindows',
  'azure vpn client': 'vpnclientwindows',
  'local network gateway': 'local-network-gateways',
  'lng': 'local-network-gateways',
  'on premise gateway': 'local-network-gateways',
  'expressroute': 'expressroute-circuits',
  'express route': 'expressroute-circuits',
  'azure expressroute': 'expressroute-circuits',
  'er circuit': 'expressroute-circuits',
  'expressroute direct': 'expressroute-direct',
  'er direct': 'expressroute-direct',
  'expressroute traffic collector': 'express-route-traffic-collector',
  'ertc': 'express-route-traffic-collector',
  
  // Load Balancing
  'load balancer': 'load-balancers',
  'lb': 'load-balancers',
  'azure load balancer': 'load-balancers',
  'public load balancer': 'load-balancers',
  'internal load balancer': 'load-balancers',
  'load balancer hub': 'load-balancer-hub',
  'lb hub': 'load-balancer-hub',
  
  // Application Gateway
  'application gateway': 'application-gateways',
  'app gateway': 'application-gateways',
  'azure application gateway': 'application-gateways',
  'agw': 'application-gateways',
  'application gateway for containers': 'application-gateway-containers',
  'agc': 'application-gateway-containers',
  'container app gateway': 'application-gateway-containers',
  
  // CDN & Front Door
  'front door': 'front-door-and-cdn-profiles',
  'azure front door': 'front-door-and-cdn-profiles',
  'afd': 'front-door-and-cdn-profiles',
  'cdn profile': 'front-door-and-cdn-profiles',
  'azure cdn': 'cdn-profiles',
  'cdn': 'cdn-profiles',
  'cdn profiles': 'cdn-profiles',
  'content delivery network': 'cdn-profiles',
  
  // Traffic Management
  'traffic manager': 'traffic-manager-profiles',
  'azure traffic manager': 'traffic-manager-profiles',
  'atm': 'traffic-manager-profiles',
  
  // Security Groups
  'nsg': 'network-security-groups',
  'network security group': 'network-security-groups',
  'azure nsg': 'network-security-groups',
  'asg': 'application-security-groups',
  'application security group': 'application-security-groups',
  'azure asg': 'application-security-groups',
  
  // Network Interfaces & IPs
  'nic': 'network-interfaces',
  'network interface': 'network-interfaces',
  'azure nic': 'network-interfaces',
  'network adapter': 'network-interfaces',
  'public ip': 'public-ip-addresses',
  'public ip address': 'public-ip-addresses',
  'azure public ip': 'public-ip-addresses',
  'classic public ip': 'public-ip-addresses-(classic)',
  'public ip prefix': 'public-ip-prefixes',
  'ip prefix': 'public-ip-prefixes',
  'reserved ip classic': 'reserved-ip-addresses-(classic)',
  'classic reserved ip': 'reserved-ip-addresses-(classic)',
  
  // Private Connectivity
  'private endpoint': 'private-endpoints',
  'azure private endpoint': 'private-endpoints',
  'private link': 'private-link',
  'azure private link': 'private-link',
  'private link service': 'private-link-service',
  'pls': 'private-link-service',
  'private link services': 'private-link-services',
  
  // Routing
  'route table': 'route-tables',
  'azure route table': 'route-tables',
  'udr': 'route-tables',
  'route filter': 'route-filters',
  'azure route filter': 'route-filters',
  
  // Network Management
  'network watcher': 'network-watcher',
  'azure network watcher': 'network-watcher',
  'bastion': 'bastions',
  'azure bastion': 'bastions',
  'bastion host': 'bastions',
  'jump host': 'bastions',
  'nat gateway': 'nat',
  'azure nat': 'nat',
  'nat service': 'nat',
  'ddos': 'ddos-protection-plans',
  'ddos protection': 'ddos-protection-plans',
  'azure ddos': 'ddos-protection-plans',
  'ddos plan': 'ddos-protection-plans',
  
  // Firewall & WAF
  'waf': 'web-application-firewall-policies(waf)',
  'web application firewall': 'web-application-firewall-policies(waf)',
  'azure waf': 'web-application-firewall-policies(waf)',
  'application firewall': 'web-application-firewall-policies(waf)',
  'firewall manager': 'firewall-manager',
  'azure firewall manager': 'firewall-manager',
  'afw manager': 'firewall-manager',
  'firewall': 'firewalls',
  'azure firewall': 'firewalls',
  'afw': 'firewalls',
  'cloud firewall': 'firewalls',
  'firewall policy': 'azure-firewall-policy',
  'azure firewall policy': 'azure-firewall-policy',
  
  // WAN & Peering
  'virtual wan': 'virtual-wans',
  'vwan': 'virtual-wans',
  'azure virtual wan': 'virtual-wans',
  'sdwan': 'virtual-wans',
  'virtual wan hub': 'virtual-wan-hub',
  'vwan hub': 'virtual-wan-hub',
  'peering': 'peerings',
  'vnet peering': 'peerings',
  'virtual network peering': 'peerings',
  'peering service': 'peering-service',
  'azure peering': 'peering-service',
  
  // Other Network
  'service endpoint policy': 'service-endpoint-policies',
  'sep': 'service-endpoint-policies',
  'ip group': 'ip-groups',
  'azure ip group': 'ip-groups',
  'custom ip prefix': 'custom-ip-prefix',
  'ip prefix custom': 'custom-ip-prefix',
  'subnet': 'subnet',
  'azure subnet': 'subnet',
  'vnet subnet': 'subnet',
  'proximity placement group': 'proximity-placement-groups',
  'ppg': 'proximity-placement-groups',
  'network manager': 'network-managers',
  'azure network manager': 'network-managers',
  'anm': 'network-managers',
  'network security perimeter': 'network-security-perimeters',
  'nsp': 'network-security-perimeters',
  'network security hub': 'network-security-hub',
  'security hub': 'network-security-hub',
  'network foundation hub': 'network-foundation-hub',
  'nfh': 'network-foundation-hub',
  
  // DNS
  'dns': 'dns-zones',
  'dns zone': 'dns-zones',
  'azure dns': 'dns-zones',
  'domain name system': 'dns-zones',
  'private dns resolver': 'dns-private-resolver',
  'dns resolver': 'dns-private-resolver',
  'azure private resolver': 'dns-private-resolver',
  'dns security policy': 'dns-security-policy',
  'dns policy': 'dns-security-policy',
  'dns multistack': 'dns-multistack',
  
  // Network Appliances
  'vnet appliance': 'vnet-appliance',
  'virtual router': 'virtual-router',
  'network function manager': 'azure-network-function-manager',
  'nfm': 'azure-network-function-manager',
  'network function': 'azure-network-function-manager-functions',
  'landing zone': 'landing-zone',
  'mission landing zone': 'mission-landing-zone',
  'sonic dash': 'sonic-dash',
  'wac': 'wac',
  'windows admin center': 'wac',
  'wac installer': 'wac-installer',
  
  // ============================================================================
  // DATABASES
  // ============================================================================
  
  // SQL
  'sql database': 'sql-database',
  'azure sql': 'sql-database',
  'azure sql database': 'sql-database',
  'sql db': 'sql-database',
  'azure sql db': 'sql-database',
  'sql managed instance': 'sql-managed-instance',
  'sql mi': 'sql-managed-instance',
  'azure sql mi': 'sql-managed-instance',
  'managed instance': 'sql-managed-instance',
  'sql server': 'sql-server',
  'azure sql server': 'sql-server',
  'microsoft sql server': 'sql-server',
  'sql elastic pool': 'sql-elastic-pools',
  'elastic pool': 'sql-elastic-pools',
  'azure elastic pool': 'sql-elastic-pools',
  'sql vm': 'azure-sql-vm',
  'sql virtual machine': 'azure-sql-vm',
  'sql server on azure vm': 'azure-sql-vm',
  'sql edge': 'azure-sql-edge',
  'azure sql edge': 'azure-sql-edge',
  'iot sql': 'azure-sql-edge',
  'sql server registry': 'sql-server-registries',
  'sql fleet manager': 'sql-database-fleet-manager',
  'database fleet manager': 'sql-database-fleet-manager',
  'virtual cluster': 'virtual-clusters',
  'sql virtual cluster': 'virtual-clusters',
  'instance pool': 'instance-pools',
  'sql instance pool': 'instance-pools',
  'elastic job agent': 'elastic-job-agents',
  'sql elastic job': 'elastic-job-agents',
  
  // Open Source Databases
  'postgresql': 'azure-database-postgresql-server',
  'postgres': 'azure-database-postgresql-server',
  'azure postgres': 'azure-database-postgresql-server',
  'azure postgresql': 'azure-database-postgresql-server',
  'azure database for postgresql': 'azure-database-postgresql-server',
  'postgres server group': 'azure-database-postgresql-server-group',
  'postgresql server group': 'azure-database-postgresql-server-group',
  'flexible server': 'azure-database-postgresql-server-group',
  'mysql': 'azure-database-mysql-server',
  'azure mysql': 'azure-database-mysql-server',
  'azure database for mysql': 'azure-database-mysql-server',
  'mariadb': 'azure-database-mariadb-server',
  'azure mariadb': 'azure-database-mariadb-server',
  'maria db': 'azure-database-mariadb-server',
  'azure database for mariadb': 'azure-database-mariadb-server',
  
  // NoSQL & Big Data
  'cosmos db': 'azure-cosmos-db',
  'cosmos': 'azure-cosmos-db',
  'azure cosmos': 'azure-cosmos-db',
  'cosmosdb': 'azure-cosmos-db',
  'azure cosmosdb': 'azure-cosmos-db',
  'document db': 'azure-cosmos-db',
  'sql data warehouse': 'sql-data-warehouses',
  'sql dw': 'sql-data-warehouses',
  'azure sql data warehouse': 'sql-data-warehouses',
  'dwh': 'sql-data-warehouses',
  'synapse': 'azure-synapse-analytics',
  'synapse analytics': 'azure-synapse-analytics',
  'azure synapse': 'azure-synapse-analytics',
  'sql analytics': 'azure-synapse-analytics',
  'data explorer': 'azure-data-explorer-clusters',
  'adx': 'azure-data-explorer-clusters',
  'azure data explorer': 'azure-data-explorer-clusters',
  'kusto': 'azure-data-explorer-clusters',
  'kusto cluster': 'azure-data-explorer-clusters',
  'databricks': 'azure-databricks',
  'azure databricks': 'azure-databricks',
  'dbx': 'azure-databricks',
  'apache spark': 'azure-databricks',
  'hdinsight': 'hd-insight-clusters',
  'hd insight': 'hd-insight-clusters',
  'azure hdinsight': 'hd-insight-clusters',
  'hadoop': 'hd-insight-clusters',
  'spark cluster': 'hd-insight-clusters',
  'hdinsight aks': 'hdi-aks-cluster',
  'hdinsight on aks': 'hdi-aks-cluster',
  
  // Data Integration
  'data factory': 'data-factories',
  'adf': 'data-factories',
  'azure data factory': 'data-factories',
  'data integration': 'data-factories',
  'data lake analytics': 'data-lake-analytics',
  'azure data lake analytics': 'data-lake-analytics',
  'u-sql': 'data-lake-analytics',
  'data lake store': 'data-lake-store-gen1',
  'data lake storage gen1': 'data-lake-store-gen1',
  'adls gen1': 'data-lake-store-gen1',
  'data lake storage gen 1': 'data-lake-storage-gen1',
  
  // Cache
  'redis': 'cache-redis',
  'redis cache': 'cache-redis',
  'azure cache for redis': 'cache-redis',
  'azure redis': 'cache-redis',
  'azure managed redis': 'azure-managed-redis',
  'managed redis cache': 'azure-managed-redis',
  
  // Other Databases
  'managed database': 'managed-database',
  'managed db': 'managed-database',
  'cassandra': 'managed-instance-apache-cassandra',
  'azure cassandra': 'managed-instance-apache-cassandra',
  'managed cassandra': 'managed-instance-apache-cassandra',
  'dms': 'azure-database-migration-services',
  'database migration service': 'azure-database-migration-services',
  'azure dms': 'azure-database-migration-services',
  'data migration': 'azure-database-migration-services',
  
  // ============================================================================
  // AI + MACHINE LEARNING
  // ============================================================================
  
  'openai': 'azure-openai',
  'azure openai': 'azure-openai',
  'gpt': 'azure-openai',
  'chatgpt': 'azure-openai',
  'dall-e': 'azure-openai',
  'whisper': 'azure-openai',
  'cognitive services': 'cognitive-services',
  'azure cognitive services': 'cognitive-services',
  'ai services': 'cognitive-services',
  'cognitive api': 'cognitive-services',
  'ai studio': 'ai-studio',
  'azure ai studio': 'ai-studio',
  
  // Machine Learning
  'ml': 'machine-learning',
  'machine learning': 'machine-learning',
  'azure ml': 'machine-learning',
  'azure machine learning': 'machine-learning',
  'ml workspace': 'machine-learning',
  'ml studio': 'machine-learning-studio-workspaces',
  'ml studio workspace': 'machine-learning-studio-workspaces',
  'azure ml studio classic': 'machine-learning-studio-workspaces',
  'ml studio web service plan': 'machine-learning-studio-web-service-plans',
  'ml classic plan': 'machine-learning-studio-web-service-plans',
  'ml studio web service': 'machine-learning-studio-(classic)-web-services',
  'ml classic web service': 'machine-learning-studio-(classic)-web-services',
  'applied ai': 'azure-applied-ai-services',
  'azure applied ai': 'azure-applied-ai-services',
  'ai services applied': 'azure-applied-ai-services',
  
  // Search & Vision
  'cognitive search': 'cognitive-search',
  'azure search': 'cognitive-search',
  'azure cognitive search': 'cognitive-search',
  'ai search': 'cognitive-search',
  'serverless search': 'serverless-search',
  'azure serverless search': 'serverless-search',
  'computer vision': 'computer-vision',
  'azure computer vision': 'computer-vision',
  'image recognition': 'computer-vision',
  'ocr': 'computer-vision',
  'custom vision': 'custom-vision',
  'azure custom vision': 'custom-vision',
  'custom image recognition': 'custom-vision',
  'face api': 'face-apis',
  'face detection': 'face-apis',
  'azure face': 'face-apis',
  'facial recognition': 'face-apis',
  
  // Language & Speech
  'content moderator': 'content-moderators',
  'content moderation': 'content-moderators',
  'azure content moderator': 'content-moderators',
  'speech': 'speech-services',
  'speech service': 'speech-services',
  'azure speech': 'speech-services',
  'speech to text': 'speech-services',
  'text to speech': 'speech-services',
  'luis': 'language-understanding',
  'language understanding': 'language-understanding',
  'azure luis': 'language-understanding',
  'conversational ai': 'language-understanding',
  'language': 'language',
  'language service': 'language',
  'azure language': 'language',
  'text analytics': 'language',
  'qna maker': 'qna-makers',
  'question answering': 'qna-makers',
  'azure qna': 'qna-makers',
  'knowledge base': 'qna-makers',
  'translator': 'translator-text',
  'text translation': 'translator-text',
  'azure translator': 'translator-text',
  'machine translation': 'translator-text',
  'immersive reader': 'immersive-readers',
  'azure immersive reader': 'immersive-readers',
  
  // AI Services
  'anomaly detector': 'anomaly-detector',
  'azure anomaly detector': 'anomaly-detector',
  'form recognizer': 'form-recognizers',
  'document intelligence': 'form-recognizers',
  'azure form recognizer': 'form-recognizers',
  'content safety': 'content-safety',
  'azure content safety': 'content-safety',
  'content filtering': 'content-safety',
  'personalizer': 'personalizers',
  'azure personalizer': 'personalizers',
  'recommendation': 'personalizers',
  'bonsai': 'bonsai',
  'azure bonsai': 'bonsai',
  'autonomous systems': 'bonsai',
  'bot': 'bot-services',
  'bot service': 'bot-services',
  'azure bot': 'bot-services',
  'bot framework': 'bot-services',
  'chatbot': 'bot-services',
  
  // Other AI
  'genomics': 'genomics',
  'azure genomics': 'genomics',
  'dna sequencing': 'genomics',
  'genomics account': 'genomics-accounts',
  'microsoft genomics': 'genomics-accounts',
  'batch ai': 'batch-ai',
  'azure batch ai': 'batch-ai',
  'ai training': 'batch-ai',
  'experimentation studio': 'azure-experimentation-studio',
  'azure experimentation': 'azure-experimentation-studio',
  'a-b testing': 'azure-experimentation-studio',
  'object understanding': 'azure-object-understanding',
  'azure object understanding': 'azure-object-understanding',
  'metrics advisor': 'metrics-advisor',
  'azure metrics advisor': 'metrics-advisor',
  'cognitive services decisions': 'cognitive-services-decisions',
  'decision service': 'cognitive-services-decisions',
  
  // ============================================================================
  // IDENTITY & SECURITY
  // ============================================================================
  
  // Entra / Azure AD
  'entra': 'entra-id',
  'entra id': 'entra-id',
  'azure ad': 'entra-id',
  'azure active directory': 'entra-id',
  'aad': 'entra-id',
  'active directory': 'entra-id',
  'entra domain services': 'entra-domain-services',
  'azure ad domain services': 'entra-domain-services',
  'aadds': 'entra-domain-services',
  'domain services': 'entra-domain-services',
  'entra connect': 'entra-connect',
  'azure ad connect': 'entra-connect',
  'aad connect': 'entra-connect',
  'entra connect sync': 'entra-connect-sync',
  'azure ad connect sync': 'entra-connect-sync',
  'aadc sync': 'entra-connect-sync',
  'entra connect health': 'entra-connect-health',
  'azure ad connect health': 'entra-connect-health',
  'entra id protection': 'entra-id-protection',
  'azure ad identity protection': 'entra-id-protection',
  'identity protection': 'entra-id-protection',
  'risky sign-ins': 'entra-identity-risky-signins',
  'entra risky signins': 'entra-identity-risky-signins',
  'suspicious signins': 'entra-identity-risky-signins',
  'risky users': 'entra-identity-risky-users',
  'entra risky users': 'entra-identity-risky-users',
  'compromised users': 'entra-identity-risky-users',
  'entra roles': 'entra-identity-roles-and-administrators',
  'directory roles': 'entra-identity-roles-and-administrators',
  'admin roles': 'entra-identity-roles-and-administrators',
  'global administrator': 'entra-identity-roles-and-administrators',
  'custom roles': 'entra-identity-custom-roles',
  'entra custom roles': 'entra-identity-custom-roles',
  'licenses': 'entra-identity-licenses',
  'entra licenses': 'entra-identity-licenses',
  'azure ad licenses': 'entra-identity-licenses',
  
  // Managed Identities
  'managed identity': 'entra-managed-identities',
  'managed identities': 'entra-managed-identities',
  'msi': 'entra-managed-identities',
  'system assigned identity': 'entra-managed-identities',
  'user assigned identity': 'entra-managed-identities',
  'pim': 'entra-privleged-identity-management',
  'privileged identity management': 'entra-privleged-identity-management',
  'azure ad pim': 'entra-privleged-identity-management',
  'entra pim': 'entra-privleged-identity-management',
  'verified id': 'entra-verified-id',
  'entra verified id': 'entra-verified-id',
  'decentralized identity': 'entra-verified-id',
  'verifiable credentials': 'entra-verified-id',
  
  // Secure Access
  'entra private access': 'entra-private-access',
  'private access': 'entra-private-access',
  'secure private access': 'entra-private-access',
  'entra internet access': 'entra-internet-access',
  'secure internet access': 'entra-internet-access',
  'global secure access': 'entra-global-secure-access',
  'entra gsa': 'entra-global-secure-access',
  'microsoft security service edge': 'entra-global-secure-access',
  'external identities': 'external-identities',
  'azure ad b2b': 'external-identities',
  'b2b collaboration': 'external-identities',
  'guest users': 'external-identities',
  'b2c': 'azure-ad-b2c',
  'azure ad b2c': 'azure-ad-b2c',
  'azure b2c': 'azure-ad-b2c',
  'identity experience framework': 'azure-ad-b2c',
  
  // Identity Management
  'app registration': 'app-registrations',
  'application registration': 'app-registrations',
  'app reg': 'app-registrations',
  'enterprise application': 'enterprise-applications',
  'enterprise applications': 'enterprise-applications',
  'service principal': 'enterprise-applications',
  'user': 'users',
  'aad user': 'users',
  'entra user': 'users',
  'directory user': 'users',
  'group': 'groups',
  'aad group': 'groups',
  'entra group': 'groups',
  'security group': 'groups',
  'administrative unit': 'administrative-units',
  'administrative units': 'administrative-units',
  'au': 'administrative-units',
  'identity governance': 'identity-governance',
  'entra governance': 'identity-governance',
  'access reviews': 'identity-governance',
  'access packages': 'identity-governance',
  'conditional access': 'conditional-access',
  'azure ad conditional access': 'conditional-access',
  'ca policy': 'conditional-access',
  'mfa': 'multi-factor-authentication',
  'multi factor authentication': 'multi-factor-authentication',
  'two factor authentication': 'multi-factor-authentication',
  '2fa': 'multi-factor-authentication',
  
  // Security
  'key vault': 'key-vaults',
  'keyvault': 'key-vaults',
  'azure key vault': 'key-vaults',
  'akv': 'key-vaults',
  'secret management': 'key-vaults',
  'key': 'keys',
  'azure key': 'keys',
  'key management': 'keys',
  'dedicated hsm': 'dedicated-hsm',
  'azure dedicated hsm': 'dedicated-hsm',
  'hardware security module': 'dedicated-hsm',
  'certificate authority': 'certificate-authority',
  'ca': 'certificate-authority',
  'azure ca': 'certificate-authority',
  'confidential ledger': 'confidential-ledgers',
  'azure confidential ledger': 'confidential-ledgers',
  'acl': 'confidential-ledgers',
  'attestation': 'azure-attestation',
  'azure attestation': 'azure-attestation',
  'maa': 'azure-attestation',
  'security': 'security',
  'azure security': 'security',
  'microsoft security': 'security',
  'secure score': 'identity-secure-score',
  'identity secure score': 'identity-secure-score',
  'security score': 'identity-secure-score',
  'customer lockbox': 'customer-lockbox-for-microsoft-azure',
  'lockbox': 'customer-lockbox-for-microsoft-azure',
  'azure lockbox': 'customer-lockbox-for-microsoft-azure',
  'verification service': 'verification-as-a-service',
  'verifiable credential': 'verifiable-credentials',
  'vc': 'verifiable-credentials',
  
  // Defender & Sentinel
  'defender': 'microsoft-defender-for-cloud',
  'defender for cloud': 'microsoft-defender-for-cloud',
  'azure defender': 'microsoft-defender-for-cloud',
  'security center': 'microsoft-defender-for-cloud',
  'azure security center': 'microsoft-defender-for-cloud',
  'mdc': 'microsoft-defender-for-cloud',
  'defender for iot': 'microsoft-defender-for-iot',
  'iot defender': 'microsoft-defender-for-iot',
  'industrial iot security': 'microsoft-defender-for-iot',
  'defender easm': 'microsoft-defender-easm',
  'external attack surface management': 'microsoft-defender-easm',
  'sentinel': 'azure-sentinel',
  'azure sentinel': 'azure-sentinel',
  'microsoft sentinel': 'azure-sentinel',
  'siem': 'azure-sentinel',
  'soar': 'azure-sentinel',
  
  // Azure Information Protection
  'aip': 'azure-information-protection',
  'azure information protection': 'azure-information-protection',
  'information protection': 'azure-information-protection',
  'rms': 'azure-information-protection',
  
  // ============================================================================
  // IOT
  // ============================================================================
  
  'iot hub': 'iot-hub',
  'iot': 'iot-hub',
  'azure iot hub': 'iot-hub',
  'iothub': 'iot-hub',
  'iot device management': 'iot-hub',
  'iot edge': 'iot-edge',
  'azure iot edge': 'iot-edge',
  'edge computing': 'iot-edge',
  'edge runtime': 'iot-edge',
  'iot central': 'iot-central-applications',
  'azure iot central': 'iot-central-applications',
  'iot saas': 'iot-central-applications',
  'iot application': 'iot-central-applications',
  'dps': 'device-provisioning-services',
  'device provisioning service': 'device-provisioning-services',
  'iot dps': 'device-provisioning-services',
  'device provisioning': 'device-provisioning-services',
  'azure maps': 'azure-maps-accounts',
  'maps': 'azure-maps-accounts',
  'location services': 'azure-maps-accounts',
  'mapping': 'azure-maps-accounts',
  'time series insights': 'time-series-insights-environments',
  'tsi': 'time-series-insights-environments',
  'azure tsi': 'time-series-insights-environments',
  'time series database': 'time-series-insights-environments',
  'tsi event source': 'time-series-insights-event-sources',
  'time series event source': 'time-series-insights-event-sources',
  'tsi access policy': 'time-series-insights-access-policies',
  'time series access policy': 'time-series-insights-access-policies',
  'time series dataset': 'time-series-data-sets',
  'tsi dataset': 'time-series-data-sets',
  'digital twins': 'digital-twins',
  'azure digital twins': 'digital-twins',
  'adt': 'digital-twins',
  'digital twin': 'digital-twins',
  'device update': 'device-update-iot-hub',
  'iot device update': 'device-update-iot-hub',
  'adu': 'device-update-iot-hub',
  'industrial iot': 'industrial-iot',
  'iiot': 'industrial-iot',
  'azure industrial iot': 'industrial-iot',
  'windows 10 iot': 'windows10-core-services',
  'iot core': 'windows10-core-services',
  'windows iot': 'windows10-core-services',
  'sphere': 'azure-sphere',
  'azure sphere': 'azure-sphere',
  'iot sphere': 'azure-sphere',
  'secure iot': 'azure-sphere',
  'iot operations': 'azure-iot-operations',
  'azure iot operations': 'azure-iot-operations',
  'aio': 'azure-iot-operations',
  'notification hub': 'notification-hubs',
  'azure notification hub': 'notification-hubs',
  'push notifications': 'notification-hubs',
  'push hub': 'notification-hubs',
  'notification hub namespace': 'notification-hub-namespaces',
  'push namespace': 'notification-hub-namespaces',
  
  // ============================================================================
  // INTEGRATION
  // ============================================================================
  
  'logic app': 'logic-apps',
  'logic apps': 'logic-apps',
  'azure logic apps': 'logic-apps',
  'integration workflow': 'logic-apps',
  'logic apps custom connector': 'logic-apps-custom-connector',
  'custom connector': 'logic-apps-custom-connector',
  'logic app template': 'logic-apps-template',
  'service bus': 'azure-service-bus',
  'azure service bus': 'azure-service-bus',
  'messaging': 'azure-service-bus',
  'queue': 'azure-service-bus',
  'topic': 'azure-service-bus',
  'event grid': 'event-grid-topics',
  'event grid topic': 'event-grid-topics',
  'azure event grid': 'event-grid-topics',
  'event grid domain': 'event-grid-domains',
  'event grid domains': 'event-grid-domains',
  'event grid subscription': 'event-grid-subscriptions',
  'event grid subscriptions': 'event-grid-subscriptions',
  'system topic': 'system-topic',
  'event grid system topic': 'system-topic',
  'partner topic': 'partner-topic',
  'event grid partner topic': 'partner-topic',
  'partner namespace': 'partner-namespace',
  'partner registration': 'partner-registration',
  'event hub': 'event-hubs',
  'event hubs': 'event-hubs',
  'azure event hubs': 'event-hubs',
  'event streaming': 'event-hubs',
  'event hub cluster': 'event-hub-clusters',
  'event hubs dedicated': 'event-hub-clusters',
  'api management': 'api-management-services',
  'apim': 'api-management-services',
  'azure api management': 'api-management-services',
  'api connection': 'api-connections',
  'azure api connection': 'api-connections',
  'app configuration': 'app-configuration',
  'azure app configuration': 'app-configuration',
  'feature flag': 'app-configuration',
  'integration account': 'integration-accounts',
  'azure integration account': 'integration-accounts',
  'b2b integration': 'integration-accounts',
  'integration service environment': 'integration-service-environments',
  'ise': 'integration-service-environments',
  'integration environment': 'integration-environments',
  'relay': 'relays',
  'azure relay': 'relays',
  'hybrid connection': 'relays',
  'wcf relay': 'relays',
  'data catalog': 'azure-data-catalog',
  'azure data catalog': 'azure-data-catalog',
  'data discovery': 'azure-data-catalog',
  'saas': 'software-as-a-service',
  'software as a service': 'software-as-a-service',
  'azure saas': 'software-as-a-service',
  'sendgrid': 'sendgrid-accounts',
  'sendgrid account': 'sendgrid-accounts',
  'email service': 'sendgrid-accounts',
  'fhir': 'azure-api-for-fhir',
  'azure api for fhir': 'azure-api-for-fhir',
  'healthcare api': 'azure-api-for-fhir',
  'fast healthcare': 'azure-api-for-fhir',
  'business process tracking': 'business-process-tracking',
  'process tracking': 'business-process-tracking',
  'data gateway': 'on-premises-data-gateways',
  'on premises gateway': 'on-premises-data-gateways',
  'power bi gateway': 'on-premises-data-gateways',
  
  // ============================================================================
  // DEVOPS & DEVELOPMENT
  // ============================================================================
  
  'devops': 'azure-devops',
  'azure devops': 'azure-devops',
  'ado': 'azure-devops',
  'azure devops services': 'azure-devops',
  'devops server': 'azure-devops',
  'managed devops pool': 'managed-devops-pools',
  'devops pool': 'managed-devops-pools',
  'devops starter': 'devops-starter',
  'azure devops starter': 'devops-starter',
  'app insights': 'application-insights',
  'application insights': 'application-insights',
  'azure monitor application insights': 'application-insights',
  'monitor': 'application-insights',
  'azure monitor': 'application-insights',
  'monitoring': 'application-insights',
  'monitor pipeline': 'azure-monitor-pipeline',
  'azure monitor pipeline': 'azure-monitor-pipeline',
  'workbook': 'azure-workbooks',
  'azure workbooks': 'azure-workbooks',
  'grafana alternative': 'azure-workbooks',
  'workbooks': 'workbooks',
  'grafana workbook': 'workbooks',
  'log analytics': 'log-analytics-workspaces',
  'log analytics workspace': 'log-analytics-workspaces',
  'law': 'log-analytics-workspaces',
  'azure log analytics': 'log-analytics-workspaces',
  'query pack': 'log-analytics-query-pack',
  'log analytics query pack': 'log-analytics-query-pack',
  'metrics': 'metrics',
  'azure metrics': 'metrics',
  'metric explorer': 'metrics',
  'alert': 'alerts',
  'alerts': 'alerts',
  'azure alerts': 'alerts',
  'monitoring alerts': 'alerts',
  'smart detector': 'smart-detector-alert-rule',
  'activity log': 'activity-log',
  'azure activity log': 'activity-log',
  'audit log': 'activity-log',
  'diagnostic setting': 'diagnostics-settings',
  'diagnostics': 'diagnostics-settings',
  'change analysis': 'change-analysis',
  'azure change analysis': 'change-analysis',
  'monitor dashboard': 'azure-monitor-dashboard',
  'health model': 'monitor-health-models',
  'monitor issue': 'monitor-issues',
  
  // Testing & Dev Tools
  'cloudtest': 'cloudtest',
  'azure cloudtest': 'cloudtest',
  'load testing': 'azure-load-testing',
  'azure load testing': 'azure-load-testing',
  'jmeter': 'azure-load-testing',
  'load testing service': 'load-testing',
  'devtest lab': 'devtest-labs',
  'devtest labs': 'devtest-labs',
  'azure devtest labs': 'devtest-labs',
  'dev test lab': 'devtest-labs',
  'lab service': 'lab-services',
  'lab services': 'lab-services',
  'azure lab services': 'lab-services',
  'classroom lab': 'lab-services',
  'lab account': 'lab-accounts',
  'dev console': 'dev-console',
  'developer console': 'dev-console',
  'dev box': 'microsoft-dev-box',
  'microsoft dev box': 'microsoft-dev-box',
  'cloud pc for dev': 'microsoft-dev-box',
  'deployment environment': 'azure-deployment-environments',
  'azure deployment environments': 'azure-deployment-environments',
  'ade': 'azure-deployment-environments',
  'chaos studio': 'azure-chaos-studio',
  'azure chaos studio': 'azure-chaos-studio',
  'chaos engineering': 'azure-chaos-studio',
  'code optimization': 'code-optimization',
  'web test': 'web-test',
  'availability test': 'web-test',
  'url ping test': 'web-test',
  'app testing': 'azure-app-testing',
  'azure app testing': 'azure-app-testing',
  'test base': 'test-base',
  'azure test base': 'test-base',
  'cloud shell': 'azure-cloud-shell',
  'azure cloud shell': 'azure-cloud-shell',
  'browser shell': 'azure-cloud-shell',
  'toolchain orchestrator': 'toolchain-orchestrator',
  'dev tunnels': 'azure-dev-tunnels',
  'azure dev tunnels': 'azure-dev-tunnels',
  
  // ============================================================================
  // ANALYTICS
  // ============================================================================
  
  'power bi': 'power-bi-embedded',
  'powerbi': 'power-bi-embedded',
  'power bi embedded': 'power-bi-embedded',
  'azure power bi': 'power-bi-embedded',
  'power platform': 'power-platform',
  'azure power platform': 'power-platform',
  'powerapps': 'power-platform',
  'power automate': 'power-platform',
  'analysis services': 'analysis-services',
  'azure analysis services': 'analysis-services',
  'aas': 'analysis-services',
  'ssas': 'analysis-services',
  'stream analytics': 'stream-analytics-jobs',
  'azure stream analytics': 'stream-analytics-jobs',
  'real time analytics': 'stream-analytics-jobs',
  'endpoint analytics': 'endpoint-analytics',
  'microsoft endpoint analytics': 'endpoint-analytics',
  
  // ============================================================================
  // MANAGEMENT & GOVERNANCE
  // ============================================================================
  
  'resource group': 'resource-groups',
  'resource groups': 'resource-groups',
  'rg': 'resource-groups',
  'azure resource group': 'resource-groups',
  'resource group list': 'resource-group-list',
  'subscription': 'subscriptions',
  'subscriptions': 'subscriptions',
  'azure subscription': 'subscriptions',
  'sub': 'subscriptions',
  'management group': 'management-groups',
  'management groups': 'management-groups',
  'azure management group': 'management-groups',
  'resource explorer': 'resource-explorer',
  'azure resource explorer': 'resource-explorer',
  'resource graph': 'resource-graph-explorer',
  'azure resource graph': 'resource-graph-explorer',
  'arg': 'resource-graph-explorer',
  'resource mover': 'resource-mover',
  'azure resource mover': 'resource-mover',
  'resource guard': 'resource-guard',
  'linked resource': 'resource-linked',
  'blueprint': 'blueprints',
  'blueprints': 'blueprints',
  'azure blueprints': 'blueprints',
  'infrastructure as code': 'blueprints',
  'policy': 'policy',
  'azure policy': 'policy',
  'governance': 'policy',
  
  // Cost Management
  'cost management': 'cost-management',
  'azure cost management': 'cost-management',
  'cost analysis': 'cost-management',
  'billing': 'cost-management-and-billing',
  'cost management billing': 'cost-management-and-billing',
  'cost alert': 'cost-alerts',
  'cost alerts': 'cost-alerts',
  'billing alert': 'cost-alerts',
  'budget alert': 'cost-alerts',
  'cost explorer': 'cost-analysis',
  'budget': 'cost-budgets',
  'cost budget': 'cost-budgets',
  'azure budget': 'cost-budgets',
  'budgets': 'cost-budgets',
  'cost export': 'cost-export',
  'billing export': 'cost-export',
  'reservation': 'reservations',
  'reservations': 'reservations',
  'azure reservation': 'reservations',
  'reserved instances': 'reservations',
  'ri': 'reservations',
  'savings plan': 'savings-plans',
  'savings plans': 'savings-plans',
  'azure savings plan': 'savings-plans',
  'compute savings': 'savings-plans',
  'reserved capacity': 'reserved-capacity',
  'capacity reservation': 'capacity-reservation-groups',
  'capacity reservation groups': 'capacity-reservation-groups',
  'scheduled actions': 'scheduled-actions',
  'quota': 'azure-quotas',
  'azure quota': 'azure-quotas',
  'service quota': 'azure-quotas',
  'subscription quota': 'azure-quotas',
  
  // Advisor & Health
  'advisor': 'advisor',
  'azure advisor': 'advisor',
  'recommendations': 'advisor',
  'service health': 'service-health',
  'azure service health': 'service-health',
  'data collection rule': 'data-collection-rules',
  'dcr': 'data-collection-rules',
  'automation': 'automation-accounts',
  'azure automation': 'automation-accounts',
  'automation account': 'automation-accounts',
  'runbook': 'automation-accounts',
  'scheduler': 'scheduler-job-collections',
  'azure scheduler': 'scheduler-job-collections',
  'scheduled jobs': 'scheduler-job-collections',
  'solution': 'solutions',
  'solutions': 'solutions',
  'monitoring solution': 'solutions',
  'service provider': 'service-providers',
  'service providers': 'service-providers',
  'csp': 'service-providers',
  'cloud solution provider': 'service-providers',
  'my customers': 'my-customers',
  'customer management': 'my-customers',
  'education': 'education',
  'azure education': 'education',
  'azure for students': 'education',
  'service catalog': 'service-catalog-mad',
  'managed applications': 'service-catalog-mad',
  'mad': 'service-catalog-mad',
  'marketplace': 'marketplace',
  'azure marketplace': 'marketplace',
  'marketplace management': 'marketplace-management',
  'template spec': 'template-specs',
  'template specs': 'template-specs',
  'arm template spec': 'template-specs',
  'template': 'templates',
  'templates': 'templates',
  'arm template': 'templates',
  'resource manager template': 'templates',
  'quickstart center': 'quickstart-center',
  'getting started': 'quickstart-center',
  'dashboard': 'dashboard',
  'azure dashboard': 'dashboard',
  'portal dashboard': 'dashboard',
  'dashboard hub': 'dashboard-hub',
  'all resources': 'all-resources',
  'resource list': 'all-resources',
  'recent': 'recent',
  'recent resources': 'recent',
  'free services': 'free-services',
  'azure free': 'free-services',
  'free': 'free-services',
  'tag': 'tag',
  'tags': 'tags',
  'resource tag': 'tag',
  'azure tag': 'tag',
  'tagging': 'tags',
  'help': 'help-and-support',
  'support': 'help-and-support',
  'azure support': 'help-and-support',
  'troubleshoot': 'troubleshoot',
  'troubleshooter': 'troubleshoot',
  'preview': 'preview-features',
  'preview feature': 'preview-features',
  'azure preview': 'preview-features',
  'region': 'region-management',
  'azure region': 'region-management',
  'compliance': 'compliance',
  'azure compliance': 'compliance',
  'compliance center': 'compliance-center',
  'microsoft compliance': 'compliance-center',
  'service trust portal': 'service-trust-portal',
  'information': 'information',
  'info': 'information',
  
  // ============================================================================
  // HYBRID & MULTICLOUD
  // ============================================================================
  
  'arc': 'azure-arc',
  'azure arc': 'azure-arc',
  'resource bridge': 'azure-arc',
  'arc machine': 'arc-machines',
  'arc enabled server': 'arc-machines',
  'arc kubernetes': 'arc-kubernetes',
  'arc enabled kubernetes': 'arc-kubernetes',
  'arc data services': 'arc-data-services',
  'arc enabled data services': 'arc-data-services',
  'arc sql managed instance': 'arc-sql-managed-instance',
  'arc sql server': 'arc-sql-server',
  'arc postgresql': 'arc-postgresql',
  'azure stack': 'azure-stack',
  'stack': 'azure-stack',
  'azure local': 'azure-local',
  'azure stack hci local': 'azure-local',
  'migrate': 'azure-migrate',
  'azure migrate': 'azure-migrate',
  'migration': 'azure-migrate',
  'datamigration': 'azure-migrate',
  'azure modernization': 'azure-modernization',
  'modernization': 'azure-modernization',
  'avs': 'azure-vmware-solution',
  'azure vmware solution': 'azure-vmware-solution',
  'vmware on azure': 'azure-vmware-solution',
  'bare metal': 'bare-metal-infrastructure',
  'bmi': 'bare-metal-infrastructure',
  'modular data center': 'modular-data-center',
  'hybrid center': 'azure-hybrid-center',
  'azure hybrid center': 'azure-hybrid-center',
  'hybrid connectivity': 'hybrid-connectivity-hub',
  'lighthouse': 'azure-lighthouse',
  'azure lighthouse': 'azure-lighthouse',
  'delegated resource management': 'azure-lighthouse',
  
  // Recovery & Backup
  'recovery services vault': 'recovery-services-vaults',
  'recovery services vaults': 'recovery-services-vaults',
  'rsv': 'recovery-services-vaults',
  'backup vault': 'backup-vault',
  'backup center': 'azure-backup-center',
  'azure backup center': 'azure-backup-center',
  
  // ============================================================================
  // WEB & MOBILE
  // ============================================================================
  
  'mobile': 'mobile',
  'mobile service': 'mobile',
  'mobile engagement': 'mobile-engagement',
  'wns': 'windows-notification-services',
  'windows notification': 'windows-notification-services',
  'push notification': 'windows-notification-services',
  'web app database': 'web-app-+-database',
  'web app + db': 'web-app-+-database',
  'app space': 'app-space',
  'app space component': 'app-space-component',
  
  // ============================================================================
  // BLOCKCHAIN
  // ============================================================================
  
  'blockchain': 'azure-blockchain-service',
  'azure blockchain': 'azure-blockchain-service',
  'blockchain app': 'blockchain-applications',
  'blockchain application': 'blockchain-applications',
  'token service': 'azure-token-service',
  'abs member': 'abs-member',
  'consortium': 'consortium',
  'outbound connection': 'outbound-connection',
  
  // ============================================================================
  // INTUNE & DEVICE MANAGEMENT
  // ============================================================================
  
  'intune': 'intune',
  'microsoft intune': 'intune',
  'azure intune': 'intune',
  'endpoint manager': 'intune',
  'app protection': 'intune-app-protection',
  'intune app protection': 'intune-app-protection',
  'mam': 'intune-app-protection',
  'intune education': 'intune-for-education',
  'intune for school': 'intune-for-education',
  'device compliance': 'device-compliance',
  'compliance policy': 'device-compliance',
  'device configuration': 'device-configuration',
  'configuration profile': 'device-configuration',
  'device enrollment': 'device-enrollment',
  'autopilot': 'device-enrollment',
  'apple enrollment': 'device-enrollment',
  'device security apple': 'device-security-apple',
  'ios security': 'device-security-apple',
  'macos security': 'device-security-apple',
  'device security windows': 'device-security-windows',
  'windows security': 'device-security-windows',
  'device security google': 'device-security-google',
  'android security': 'device-security-google',
  'device': 'devices',
  'devices': 'devices',
  'managed device': 'devices',
  'client app': 'client-apps',
  'client apps': 'client-apps',
  'managed app': 'client-apps',
  'mobile app management': 'client-apps',
  'software update': 'software-updates',
  'software updates': 'software-updates',
  'windows update': 'software-updates',
  'patch management': 'software-updates',
  'security baseline': 'security-baselines',
  'security baselines': 'security-baselines',
  'compliance baseline': 'security-baselines',
  'exchange access': 'exchange-access',
  'email access': 'exchange-access',
  'ebook': 'ebooks',
  'ebooks': 'ebooks',
  'education book': 'ebooks',
  'mindaro': 'mindaro',
  'bridge to kubernetes': 'mindaro',
  
  // ============================================================================
  // SAP
  // ============================================================================
  
  'center for sap': 'azure-center-for-sap',
  'sap center': 'azure-center-for-sap',
  'virtual instance sap': 'virtual-instance-for-sap',
  'vis': 'virtual-instance-for-sap',
  'database instance sap': 'database-instance-for-sap',
  'central service sap': 'central-service-instance-for-sap',
  'monitor for sap': 'azure-monitors-for-sap-solutions',
  'sap monitor': 'azure-monitors-for-sap-solutions',
  
  // ============================================================================
  // SPECIALIZED WORKLOADS
  // ============================================================================
  
  'hpc workbench': 'azure-hpc-workbenches',
  'hpc workbenches': 'azure-hpc-workbenches',
  'high performance computing': 'azure-hpc-workbenches',
  'hpc cache': 'azure-hcp-cache',
  'azure hcp cache': 'azure-hcp-cache',
  'high performance cache': 'azure-hcp-cache',
  'media services': 'azure-media-service',
  'azure media': 'azure-media-service',
  'streaming': 'azure-media-service',
  'video analyzer': 'video-analyzers',
  'video analysis': 'video-analyzers',
  'video indexer': 'azure-video-indexer',
  'azure video indexer': 'azure-video-indexer',
  'remote rendering': 'remote-rendering',
  'azure remote rendering': 'remote-rendering',
  'spatial anchor': 'spatial-anchor-accounts',
  'spatial anchors': 'spatial-anchor-accounts',
  'azure spatial anchors': 'spatial-anchor-accounts',
  'communication services': 'azure-communication-services',
  'communications': 'azure-communication-services',
  'communications gateway': 'azure-communications-gateway',
  'orbital': 'azure-orbital',
  'azure orbital': 'azure-orbital',
  'satellite': 'azure-orbital',
  'programmable connectivity': 'azure-programmable-connectable',
  'operator 5g': 'azure-operator-5g-core',
  '5g core': 'azure-operator-5g-core',
  'operator nexus': 'azure-operator-nexus',
  'operator insights': 'azure-operator-insights',
  'operator service manager': 'azure-operator-service-manager',
  'mobile network': 'mobile-networks',
  'mobile networks': 'mobile-networks',
  'private 5g': 'mobile-networks',
  '5g network': 'mobile-networks',
  
  // ============================================================================
  // DATA & ANALYTICS
  // ============================================================================
  
  'data share': 'data-shares',
  'data shares': 'data-shares',
  'azure data share': 'data-shares',
  'data share invitation': 'data-share-invitations',
  'data virtualization': 'data-virtualization',
  'purview': 'purview',
  'microsoft purview': 'purview',
  'data governance': 'purview',
  'planetary computer': 'planetary-computer-pro',
  'supply chain platform': 'open-supply-chain-platform',
  
  // ============================================================================
  // GENERAL ICONS
  // ============================================================================
  
  'block blob': 'blob-block',
  'page blob': 'blob-page',
  'branch': 'branch',
  'git branch': 'branch',
  'browser': 'browser',
  'web browser': 'browser',
  'bug': 'bug',
  'issue': 'bug',
  'build': 'builds',
  'builds': 'builds',
  'pipeline build': 'builds',
  'cache': 'cache',
  'caching': 'cache',
  'code': 'code',
  'source code': 'code',
  'commit': 'commit',
  'git commit': 'commit',
  'controls': 'controls',
  'ui controls': 'controls',
  'horizontal controls': 'controls-horizontal',
  'counter': 'counter',
  'metrics counter': 'counter',
  'cubes': 'cubes',
  'olap': 'cubes',
  'cube': 'cubes',
  'download': 'download',
  'error': 'error',
  'failure': 'error',
  'extension': 'extensions',
  'extensions': 'extensions',
  'plugin': 'extensions',
  'add-on': 'extensions',
  'file': 'file',
  'folder': 'folder-blank',
  'directory': 'folder-blank',
  'folder blank': 'folder-blank',
  'web folder': 'folder-website',
  'site folder': 'folder-website',
  'ftp': 'ftp',
  'file transfer protocol': 'ftp',
  'gear': 'gear',
  'settings': 'gear',
  'cog': 'gear',
  'globe error': 'globe-error',
  'internet error': 'globe-error',
  'globe success': 'globe-success',
  'internet success': 'globe-success',
  'globe warning': 'globe-warning',
  'internet warning': 'globe-warning',
  'guide': 'guide',
  'documentation': 'guide',
  'heart': 'heart',
  'favorite': 'heart',
  'like': 'heart',
  'picture': 'image',
  'input output': 'input-output',
  'io': 'input-output',
  'journey hub': 'journey-hub',
  'user journey': 'journey-hub',
  'launch portal': 'launch-portal',
  'open portal': 'launch-portal',
  'learn': 'learn',
  'microsoft learn': 'learn',
  'location': 'location',
  'geo': 'location',
  'log stream': 'log-streaming',
  'streaming logs': 'log-streaming',
  'management portal': 'management-portal',
  'azure portal': 'management-portal',
  'portal': 'management-portal',
  'media': 'media',
  'multimedia': 'media',
  'media file': 'media-file',
  'mesh': 'mesh-applications',
  'service mesh': 'mesh-applications',
  'module': 'module',
  'component': 'module',
  'power': 'power',
  'on/off': 'power',
  'power up': 'power-up',
  'start': 'power-up',
  'powershell': 'powershell',
  'ps': 'powershell',
  'azure powershell': 'powershell',
  'search': 'search',
  'find': 'search',
  'search grid': 'search-grid',
  'server farm': 'server-farm',
  'ssd': 'ssd',
  'solid state drive': 'ssd',
  'table': 'table',
  'database table': 'table',
  'tfs': 'tfs-vc-repository',
  'team foundation server': 'tfs-vc-repository',
  'toolbox': 'toolbox',
  'tools': 'toolbox',
  'version': 'versions',
  'versions': 'versions',
  'versioning': 'versions',
  'workflow': 'workflow',
  'process': 'workflow',
  'backlog': 'backlog',
  'agile backlog': 'backlog',
  'deployment slot': 'web-slots',
  'web slot': 'web-slots',
  'staging slot': 'web-slots',
  'web job': 'web-jobs',
  'web jobs': 'web-jobs',
  'webjob': 'web-jobs',
  'background job': 'web-jobs',
  'website staging': 'website-staging',
  'staging': 'website-staging',
  'staging website': 'website-staging',
  
  // ============================================================================
  // ADDITIONAL SERVICES
  // ============================================================================
  
  'consumption commitment': 'azure-consumption-commitment',
  'azure consumption commitment': 'azure-consumption-commitment',
  'api center': 'api-center',
  'api proxy': 'api-proxy',
  'resource management private link': 'resource-management-private-link',
  'resources provider': 'resources-provider',
  'targets management': 'targets-management',
}

export default AZURE_ICON_ALIASES
